### ISSUE TITLE
How do I change the text, 'Credit card acceptance is pending'

### ISSUE THREAD

**Issue by maxrosecollins** [RailsApps/rails-stripe-membership-saas#112]
I don't think this is descriptive enough, the customer should know it has been declined.

**Comment by DanielKehoe** [comment]
Just do a global search on the application files. You'll find it in *app/views/devise/registrations/new.html.erb*.

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
