### ISSUE TITLE
Yearly subscriptions and Rails 4

### ISSUE THREAD

**Issue by drewpotter** [RailsApps/rails-stripe-membership-saas#113]
Hello,

I was wondering if this solution works for yearly subscriptions?

Also, I am using Rails 4 and wondered if I could use this in my existing Rails 4 App?

Thanks,

Drew

**Comment by DanielKehoe** [comment]
Stripe allows you to set the billing interval as yearly if you wish. The current version of the app was written for Rails 3.2. I advise to wait for an updated version (which will use the Payola gem), coming within the month.

**Comment by albertpak** [comment]
Im in a same boat right now, tried to "morph" it to be used with Rails 4.2, and running into an issue when `update_stripe' method raises an error that stripe_token is not present...after logging all vars and responses and what gets submitted - do see that stripe_token gets assigned to a user[stripe_token], but method doesn't see it...

@DanielKehoe any idea what could be causing it?

**Comment by albertpak** [comment]
Looking at the logs and what gets submitted, I do see that user[stripe_token] is there, but this line keeps raising issue:

```ruby
...
if !stripe_token.present?
  raise "Stripe token not present. Can't create account."
end
...
```

![user_create_error](https://cloud.githubusercontent.com/assets/1485687/6511013/73a20a7a-c32f-11e4-88cd-0504c9536188.jpg)

**Comment by albertpak** [comment]
Nvm, fixed the error - was an error on my part - forgot that in new Devise had to allow Stripe token parameter for Devise to handle. @DanielKehoe started reading your other [tutorial](https://tutorials.railsapps.org/tutorials/rails-stripe-coupons#stripe-integration) and it dawned upon me.

Been looking into Payola gem also and looking forward to your implementation of it.

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
