### ISSUE TITLE
Seed Subscription Plans Error

### ISSUE THREAD

**Issue by joesaundersak** [RailsApps/rails-stripe-membership-saas#132]
I was getting errors at this step and discovered that the interval should be 'month' not 'monthly'...
Here's the code I'm referring to in the Seed Subscription Plans section: 
`s1 = Plan.new(name:'Silver', stripe_id:'silver', interval:'monthly', amount: 900)`

To get it to work, I had to change it to:
`s1 = Plan.new(name:'Silver', stripe_id:'silver', interval:'month', amount: 900)`

**Comment by DanielKehoe** [comment]
Thank you for catching that. That's an error in the tutorial. It's correct in the application code. I'll make the correction in the next revision of the tutorial.
