### ISSUE TITLE
Coupons and Free Accounts - Feature Request

### ISSUE THREAD

**Issue by ThreeWest** [RailsApps/rails-stripe-membership-saas#140]
Hi again,

Anyway to add coupons and create free accounts using this app?

I don't do free trials but I would like to offer coupons to a select group and setup free accounts for testers.

**Comment by DanielKehoe** [comment]
The rails-stripe-coupons stater app provides an example. You might be able to combine the apps.

**Comment by mazhar5012** [comment]
Thanks for the solution, i need to [check it](https://github.com/mazhar5012/recurring-subscription-billing)

**Comment by ThreeWest** [comment]
Ok. Thanks. I'll check it out. I'm thinking of an alternative to Payola as of now but if I work those two together, I'll post and update or something.

**Comment by DanielKehoe** [comment]
@ThreeWest thanks for offering the feedback.

**Comment by archonic** [comment]
I wouldn't mind seeing a feature or some documentation on providing a free account with Payola. It's a pretty common aspect of SaaS.

**Comment by ThreeWest** [comment]
Yeah. Looking at all the Payola files there are lots of standard SaaS features available but no documentation.

**Comment by DanielKehoe** [comment]
The limited documentation for the Payola gem has been a challenge. If there's interest, I may try to implement this application without the Payola gem.

**Comment by ThreeWest** [comment]
Well, I am definitely interested in having more than one option for Stripe payment processing in this app. I hate to give up entirely on the Payola gem because aside from not having good support or documentation, it has a lot to offer (however useless it is without good documentation for real-world usage). The Payola gem has so many great features but that's also what makes it hard to use without good docs (and there seems to be no commitment to create any). But it also uses the "stripe" and "stripe_event" gems. At least they have some documentation. Other than that, this app is great and I've been able to turn it into a multi-tenant app using subdomains without issue. I want to do so much more with the payment system but can't because I'm a rails noob and the Payola gem doesn't have enough documentation. Payola has everything all included that one would need but no way to understand how it all works together.

**Comment by DanielKehoe** [comment]
I think that's a fair evaluation and an accurate assessment.
