### ISSUE TITLE
Application starts with a wrong flash message

### ISSUE THREAD

**Issue by nikolay12** [RailsApps/rails-stripe-membership-saas#144]
I've just forked and cloned the git rep. Did a few changes to the config directory to deal with the "missing key" issue reported recently by someone else (to make it easier to track the changes here is [my commit](https://github.com/nikolay12/rails-stripe-membership-saas/commit/d8084a227befde40cb5499ef3e6305abec478d4b)). And that was it - so I am, essentially, dealing with code from the current master branch. Once I was able to start the application at localhost:3000 I was greeted with the wrong flash message "Welcome! You have signed up successfully". It is wrong because no signup has happened - this is the equivalent of someone stumbling upon the website of the application by chance - no registration has taken yet place. I'm attaching a screenshot below:

![screen shot 2015-05-31 at 01 43 33](https://cloud.githubusercontent.com/assets/4038709/7900020/91f7d5bc-0737-11e5-9606-779a0cb61bda.png)

I know - this is not a big UI bug. But I was expecting not to see any obvious gotchas given that this code has been forked hundreds of times. Also, paying for the tutorials sort of makes you expect more ;)

**Comment by DanielKehoe** [comment]
@nikolay12 

> Also, paying for the tutorials sort of makes you expect more ;)

I'm sorry you are disappointed. I don't have your email address so please contact me directly for a refund. I don't want anyone to feel they are not getting full value from the contribution they make to support the project. Contributions keep the project going. The tutorials are my effort to give extra value to people who support the project financially.

**Comment by DanielKehoe** [comment]
@nikolay12 

> I was expecting not to see any obvious gotchas given that this code has been forked hundreds of times.

This new version of the application (using the Payola gem) is very new and has only been forked by a few people, It is open source and we are all working to identify issues and resolve them.

> I was greeted with the wrong flash message "Welcome! You have signed up successfully".

There should only be one user in the database after running ```rake db:setup``` or ```rake db:reset```. Is that the case for you? You can check by signing in as the administrator. Can you reproduce the issue you've reported?

**Comment by nikolay12** [comment]
Daniel,

The free stuff you put is great so I don't feel cheated even if there are
some gotchas here and there - it was a joke meant to justify nagging about
a relatively minor issue. Apologies if my remark sounded nasty.

Nikolay

**Comment by nikolay12** [comment]
Hi Daniel,

Thanks for the quick reply. Yes, there is one user created. I fired up the
server again and don't see the flash message anymore. It seems to happen
only the first time you fire up the server. So I wouldn't bother I'll close
the issue.

Thanks for your help.

best,
Nikolay
