### ISSUE TITLE
sign up error on new install: 'undefined method plan_class'

### ISSUE THREAD

**Issue by SylarRuby** [RailsApps/rails-stripe-membership-saas#160]
Maybe this is not compatible with rails 4.2.4 but this is disappointing: I use: git clone git://github.com/RailsApps/rails-stripe-membership-saas.git

After that it says to use rvm, as im using rbenv, so I installed ruby with rvm: "rvm install 2.2.3". All is well, then bundle install. Running "rails s" the go to localhost, sign_up link does not work! Why? Is not this a starter app?? I get `undefined method plan_class for nil:NilClass` and for the plans link:  `Couldn't find Plan`. Am I missing a step?

**Comment by DanielKehoe** [comment]
I understand your frustration but did you run ```$ rake db:seed```? Perhaps you overlooked that in the README.

**Comment by SylarRuby** [comment]
Thanks!

**Comment by DanielKehoe** [comment]
Glad to hear that solved the issue. I'll close the issue.

**Comment by roc27583** [comment]
I installed using Rails Composer, and still needed to run rake db:seed, clearly didn't work in the rails composer script! So glad this was all it was. Thanks!
