### ISSUE TITLE
Inadequate test data causing some tests to fail

### ISSUE THREAD

**Issue by yock** [RailsApps/rails-stripe-membership-saas#67]
Failing Scenarios:
cucumber features/users/sign_up_with_stripe.feature:11 # Scenario: With valid card data
cucumber features/users/sign_up_with_stripe.feature:56 # Scenario: With declined card
cucumber features/users/user_delete.feature:13 # Scenario: I create a new subscription and delete my account

This seems to be due to a recent change to require a role on signup. Manually following the test cases in the browser using the seeded dev database has the expected behavior. The failing cucumber tests all have this bit of form validation:

"No such plan: silver"

My attempts to find a place to set this for a given test failed, but I'm new to cucumber.

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
