### ISSUE TITLE
What is the difference in the repo app using Stripe's "V1" JS file vs the newer "V2"?

### ISSUE THREAD

**Issue by rceee** [RailsApps/rails-stripe-membership-saas#94]
I noticed that the javascript called remotely is Stripe's V1 (version 1 I assume).  Is there any functionality or major differences in V1 and V2 that would warrant switching/upgrading to V2?  Working through how the local JS was built now; but it's very different from Stripe's example Rails documentation.  Would switching to V2 "break" the app (require a re-write of the local JS)?

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
