### ISSUE TITLE
Webhooks setup method is deprecated; to be removed in next release

### ISSUE THREAD

**Issue by rceee** [RailsApps/rails-stripe-membership-saas#96]
From the stripe_event gem

1.1.0 (January 8, 2014)

    Deprecate StripeEvent.setup in favor of StripeEvent.configure. Remove setup at next major release.
    StripeEvent.configure yields the module to the block for configuration.
    StripeEvent.configure will raise ArgumentError unless a block is given.
    Track test coverage

Currently the app uses the code in the stripe initializer: 

    StripeEvent.setup do
    #events here

So this will break when the next release of stripe_event is released.

https://github.com/integrallis/stripe_event/blob/2f919cb45775e34d263a50778a9391387369520b/CHANGELOG.md

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
